### ISSUE TITLE
typst_asset_name not matching latest Typst releases

### ISSUE THREAD

**Issue by mintyfrankie** [yusancky/setup-typst#8]
**Description**
When running the Github action with flag `runs-on: ubuntu-latest`, the workflow returns error `Error: Asset with name typst-x86_64-unknown-linux-gnu.tar.gz not found!`

**How to reproduce**
With the code below:

```
name: Compile PDFs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Typst
      uses: yusancky/setup-typst@v1
      id: setup-typst
      with:
        version: 'v0.5.0'
    - run: typst compile cv.typ
    - run: typst compile letter.typ
```
**Potential reason**
Recent Typst releases have renamed the asset file from `typst-x86_64-unknown-linux-gnu.tar.gz` to `typst-x86_64-unknown-linux-musl.tar.xz`
